### PR TITLE
#157-Part: RIG Proxy Metrics

### LINKED ISSUE #157: RIG specific prometheus metrics
This issue is supposted to cover implementation of RIG specifc metrics.

1. implement "setup" of metrics within the instrumenter modules under `rig_metrics/lib/rig_metrics/*` Those are already implemented for the planned metrics, but commented out right now to avoid exposing not working metrics
2. implement metrics triggers for the varying use cases in the other otp apps (might differ per metrics). For this a dependency to rig_metrics will be required in the other otp apps

**Metrics planned as of latest discussion:**

RigProxyInstrumenter

* rig_current_session_count --> As Prometheus Gauge
* rig_current_subscription_count --> As Prometheus Gauge
* rig_current_open_proxy_connection_count --> As Prometheus Gauge
* rig_proxy_requests_total --> As Prometheus Counter

RigEventhubInstrumenter

* rig_processed_events_total --> As Prometheus counter + Label Node (e.g. Kafka, etc)
* rig_forwarded_events_total --> As Prometheus counter + Label Node (e.g. Kafka, etc)
* rig_dropped_events_total --> As Prometheus counter + Label Node (e.g. Kafka, etc)

RigControlInstrumenter

* rig_current_session_blacklisted_count --> As Prometheus Gauge
* rig_current_routes_configured_count --> As Prometheus Gauge

**Further Metric ideas:**
- Messages_total
- Messages_Error
- Latency
- Throughput
- etc.

### PR DESCRIPTION
**Pull request by jakobwgnr**
This is a partial implementation of #157 implementing the Metrics for the Proxy. #157 will remain open for now.

### CODE REVIEW

File: apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex [hunk 1]
```diff
@@ -84,12 +106,22 @@ defmodule RigInboundGateway.ApiProxy.Handler.Http do
...
         |> Conn.put_resp_content_type("application/json")
         |> Conn.send_resp(:ok, response)
     after
       response_timeout ->
+        ProxyMetrics.count_proxy_request(
+          conn.method,
+          request_path,
+          "http",
+          response_from,
+          "gateway_timeout"
```
Comment (kevinbader) [inline apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: perhaps it would make sense to make a distinction between a gateway timeout with respect to the forwarded http request, and a timeout that happens while waiting for the response..

File: apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/router.ex [hunk 2]
```diff
@@ -33,6 +34,14 @@ defmodule RigInboundGateway.ApiProxy.Router do
 
     case matches do
       [] ->
+        ProxyMetrics.count_proxy_request(
+          conn.method,
+          conn.request_path,
+          "N/A",
+          "N/A",
+          "not_parameterized"
```
Comment (kevinbader) [inline apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/router.ex]: isn't this simply a "not_found"?

File: docs/metrics-details.md [hunk 3]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `kafka`
+  - `kinesis`
+  - `N/A` - Not available, due to missing parametrization
+- **response_from** - Where the response is provided from. Grabbed from proxy parametrization. Following possible values:
+  - `http`
+  - `kafka`
+  - `N/A` - Not available, due to missing parametrization
+- **status** - The *internal* status for the request. Attention: this status only tracks the internal rig process status. Once forwarded we track as "ok". We expect that called services are monitored on it's own. Following possible status codes:
+  - `ok` - if forwarded successfully
+  - `not_parameterized` - if the provided `method` and/or `path` isn't parameterized
```
Comment (kevinbader) [inline docs/metrics-details.md]: as noted above, I think I'd go with not_found instead

File: docs/metrics-details.md [hunk 4]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `bad_gateway` - Could not connect to the parameterized backend (e.g. offline)
+  - `method_not_allowed` - If HTTP method is used that is not provided in the list above
```
Comment (kevinbader) [inline docs/metrics-details.md]: is there a reason to count this in addition to "not_found"?

File: docs/metrics-details.md [hunk 5]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `gateway_timeout` - On timeout for async response. May only occur if endpoint parameter `response_from` is set to `kafka` or `kinesis`
```
Comment (kevinbader) [inline docs/metrics-details.md]: ah okay so you treat connection timeouts towards the gateway as `bad_gateway` then, right? Not sure if we should use `gateway_timeout` then here, cause it has [a meaning](https://www.checkupdown.com/status/E504.html) in the http context.

File: apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/router.ex (hunk 2 above)
Comment (jakobwgnr) [reply apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/router.ex]: OK - I'll rename

File: docs/metrics-details.md (hunk 3 above)
Comment (jakobwgnr) [reply docs/metrics-details.md]: OK - I'll rename

File: docs/metrics-details.md (hunk 4 above)
Comment (jakobwgnr) [reply docs/metrics-details.md]: Hmm - I think yes. It could be the case, that a method IS parameterized, but NOTimplemented in the HTTPHandler

File: docs/metrics-details.md (hunk 5 above)
Comment (jakobwgnr) [reply docs/metrics-details.md]: Hmm - Currently `:gateway_timeout` is also used in providing the http response to the client.

If we change, than we should change both, right?

File: apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex (hunk 1 above)
Comment (jakobwgnr) [reply apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: It's `bad_gateway `& `gateway_timeout`. Isn't it?

Comment (jakobwgnr) [reply apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: fixed as discussed offline

File: docs/metrics-details.md (hunk 5 above)
Comment (jakobwgnr) [reply docs/metrics-details.md]: fixed as discussed offline

**Comment by jakobwgnr** [comment]
@kevinbader now also the tests run through smoothly

File: docs/metrics-details.md (hunk 4 above)
Comment (jakobwgnr) [reply docs/metrics-details.md]: as discussed - Removed. "Method_not_allowed" should be validated already on parametrization not on runtime.
I'll create an bug

File: CHANGELOG.md [hunk 6]
```diff
@@ -10,7 +10,8 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### Added
 
 - Increased length of header value in HTTP requests to 16384. Reason is to support long tokens such as SAML.
-
+- Added custom metrics for "API Proxy Gateway" called: rig_proxy_requests_total. For details see metrics-details.md - partially implementing [#157](https://github.com/Accenture/reactive-interaction-gateway/issues/157)
+l
```
Comment (kevinbader) [inline CHANGELOG.md]: `l`?

File: apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex [hunk 7]
```diff
@@ -84,12 +110,22 @@ defmodule RigInboundGateway.ApiProxy.Handler.Http do
 
     receive do
       {:response_received, response} ->
+        ProxyMetrics.count_proxy_request(conn.method, request_path, "http", response_from, "ok")
```
Comment (kevinbader) [inline apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: is the request_path different from `conn.request_path`?

File: CHANGELOG.md (hunk 6 above)
Comment (jakobwgnr) [reply CHANGELOG.md]: lol

File: apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex (hunk 7 above)
Comment (jakobwgnr) [reply apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: Hmm - Yes and no. The `request_path` is actually passed from the parametrization. 

But I think the HTTPHandler is only called if the `request_path` from param & the `conn.request_path` are matching (If i understood the code correctly)

Hence - It's the same. I didn't see anywhere that the `conn `was updated...

Comment (jakobwgnr) [reply apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: Do you think I should use `conn.request_path` everywhere? At least the code would shrink again, as I don't have to pass request_path everywhere

Comment (kevinbader) [reply apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: a request path may also be matched using a regular expression. To summarize, you have the following choices:

- using `conn.request_path`, we'd see what was actually requested by the client
- using the definition's request path or regex pattern, we'd see what endpoint path patterns have matched
- using the endpoint definition's ID, we'd see what endpoints definitions matched in general

Comment (jakobwgnr) [reply apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: As discussed - `conn.request_path `is probably the best option as this is the only option also usable during `not_found`. To have a consitent view I'll use that

File: CHANGELOG.md [hunk 8]
```diff
@@ -10,6 +10,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ### Added
 
 - Increased length of header value in HTTP requests to 16384. Reason is to support long tokens such as SAML.
+- Added custom metrics for "API Proxy Gateway" called: rig_proxy_requests_total. For details see metrics-details.md - partially implementing [#157](https://github.com/Accenture/reactive-interaction-gateway/issues/157)
```
Comment (kevinbader) [inline CHANGELOG.md]:
```suggestion
- [API Gateway] New custom metric: `rig_proxy_requests_total`. For details see [`metrics-details.md`](docs/metrics-details.md). [#157](https://github.com/Accenture/reactive-interaction-gateway/issues/157)
```

File: apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex [hunk 9]
```diff
@@ -43,6 +45,26 @@ defmodule RigInboundGateway.ApiProxy.Handler.Http do
           "Failed to proxy to #{inspect(url)} (#{method} #{request_path}): #{inspect(err)}"
         end)
 
+        case err.reason do
```
Comment (kevinbader) [inline apps/rig_inbound_gateway/lib/rig_inbound_gateway/api_proxy/handler/http.ex]: could you please move this to a dedicated function? For example:

```elixir
count_http_request_error(conn, err)
```

With the implementation

```elixir
defp count_http_request_error(conn, %HTTPoison.Error{reason: reason}) do
  ...
end
defp count_http_request_error(conn, :timeout) do
  ...
end
# any other errors are not counted:
defp count_http_request_error(_, _), do: :ok
```

File: docs/metrics-details.md [hunk 10]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `DELETE`
+  - `HEAD`
+  - `OPTIONS`
+- **path** - The path used for this request.
+- **target** - The target for this request. Grabbed from proxy parametrization. Following possible values:
+  - `http`
+  - `kafka`
+  - `kinesis`
+  - `N/A` - Not available, due to missing parametrization
+- **response_from** - Where the response is provided from. Grabbed from proxy parametrization. Following possible values:
```
Comment (kevinbader) [inline docs/metrics-details.md]: imho "configuration", "config" or "settings" is a bit clearer/simpler than "parametrization"

File: docs/metrics-details.md [hunk 11]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `http`
+  - `kafka`
+  - `N/A` - Not available, due to missing parametrization
```
Comment (kevinbader) [inline docs/metrics-details.md]:
```suggestion
  - `N/A` - Not applicable, e.g., the request path is not configured.
```

File: docs/metrics-details.md [hunk 12]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+- **status** - The *internal* status for the request. Attention: this status only tracks the internal rig process status. Once forwarded we track as "ok". We expect that called services are monitored on it's own. Following possible status codes:
+  - `ok` - If forwarded successfully
```
Comment (kevinbader) [inline docs/metrics-details.md]:
```suggestion
  - `ok` - Forwarded successfully.
```

File: docs/metrics-details.md [hunk 13]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `bad_request` - If there are missing expected body parameters. Targets `kafka` and `kinesis` only.
```
Comment (kevinbader) [inline docs/metrics-details.md]:
```suggestion
  - `bad_request` - Missing body parameters (`kafka` and `kinesis` only).
```

File: docs/metrics-details.md [hunk 14]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `not_found` - If the provided `method` and/or `path` isn't found in the proxy parametrization
```
Comment (kevinbader) [inline docs/metrics-details.md]:
```suggestion
  - `not_found` - No configuration found for the given `method` and/or `path`.
```

File: docs/metrics-details.md [hunk 15]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `unreachable` - Could not connect to the parameterized backend (e.g. offline)
```
Comment (kevinbader) [inline docs/metrics-details.md]:
```suggestion
  - `unreachable` - The backend cannot be connected to (e.g., service is offline or domain cannot be resolved)
```

File: docs/metrics-details.md [hunk 16]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `request_timeout` - If service is reachable, but times out.
```
Comment (kevinbader) [inline docs/metrics-details.md]:
```suggestion
  - `request_timeout` - The service is reachable but fails to deliver a response in time.
```

File: docs/metrics-details.md [hunk 17]
```diff
@@ -12,7 +12,40 @@ This metrics can be used to be included into a monitoring platform like [**Grafa
...
+  - `response_timeout` - On timeout for async response. May only occur if endpoint parameter `response_from` is set.
```
Comment (kevinbader) [inline docs/metrics-details.md]:
```suggestion
  - `response_timeout` - The endpoint has its `response_from` parameter set and RIG times out while waiting for a response.
```

**Comment by jakobwgnr** [comment]
Hi @kevinbader review feedback implemented

File: CHANGELOG.md [hunk 18]
```diff
@@ -7,7 +7,10 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## [Unreleased]
 
-<!-- ### Added -->
+### Added
+
+- Increased length of header value in HTTP requests to 16384. Reason is to support long tokens such as SAML.
```
Comment (kevinbader) [inline CHANGELOG.md]: hm line 28/31 looks very similar...
