### PR TITLE
202 - schema registry validation

### LINKED ISSUE #202: RIG Fails when KAFKA_SCHEMA_REGISTRY_HOST not set and not running on localhost
## Summary and context

IF `KAFKA_SCHEMA_REGISTRY_HOST` is not set, RIG defaults to `localhost` if there is no schema registry running on localhost, RIG fails to proxy requests and restarts itself

## How to reproduce

**When I run RIG with these settings:**

Run RIG w/o a schema registry

If you point to valid schema registry, it works.

> Describe how your clients are set up, whether they connect via SSE or WS, etc.

**..I see the following error and/or log output:**

> Add the log output to help us determine your problem. If possible, reproduce the problem after setting the environment variable `LOG_LEVEL` to `debug`.

```
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {%MatchError{term: {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}}}, [{RigKafka.Avro, :__fetch_schema_memoize, 2, [file: 'lib/rig_kafka/avro.ex', line: 80]}, {Memoize.Cache, :do_get_or_run, 3, [file: 'lib/memoize/cache.ex', line: 107]}, {RigKafka.Avro, :decode, 2, [file: 'lib/rig_kafka/avro.ex', line: 20]}, {RigKafka.Client.GroupSubscriber, :handle_message, 4, [file: 'lib/rig_kafka/client.ex', line: 84]}, {:brod_group_subscriber, :handle_messages, 4, [file: 'src/brod_group_subscriber.erl', line: 540]}, {:brod_group_subscriber, :handle_info, 2, [file: 'src/brod_group_subscriber.erl', line: 333]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 637]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 711]}]}. This protocol is implemented for: Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Rig.Subscription, Time, URI, Version, Version.Requirement
        (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) /usr/local/src/elixir/lib/elixir/lib/string/chars.ex:22: String.Chars.to_string/1
        (logger) lib/logger/formatter.ex:166: anonymous fn/1 in Logger.Formatter.output/5
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (logger) lib/logger/formatter.ex:152: anonymous fn/6 in Logger.Formatter.format/5
        (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
        (logger) lib/logger/formatter.ex:151: Logger.Formatter.format/5
```

> A clear and concise description of what you expected to happen.

## Versions (please complete the following information):**

 - Host OS: RIG docker linux
 - Frontend node supertest
 - RIG version as shown on startup Master

### PR DESCRIPTION
**Pull request by mmacai**
## Description

- fixed schema registry validation for kafka consumer
- updated avro docs
- fixed changelog
- RIG will now raise an error when kafka event is binary and schema registry is not set - right now defaults to `nil`
- updated Avro docs to use docker instead of mix

Closes #202 

## Test

- integration and unit tests
- example from Avro docs
- sending binary message using only `KAFKA_BROKERS` config should raise an error, but not restart the consumer process

### CODE REVIEW

File: apps/rig_kafka/lib/rig_kafka/serializer.ex [hunk 1]
```diff
@@ -11,12 +11,17 @@ defmodule RigKafka.Serializer do
...
+  @spec decode_body!(any(), encode_type, opts :: []) :: any()
+  def decode_body!(body, "avro", opts) do
+    case opts[:schema_registry_host] do
+      nil -> raise "cannot decode avro message: schema registry host not set"
+      schema_registry_host -> Avro.decode(body, schema_registry_host)
+    end
   end
 
-  def decode_body(body, nil), do: body
+  def decode_body!(body, nil, _), do: body
```
Comment (kevinbader) [inline apps/rig_kafka/lib/rig_kafka/serializer.ex]: can this be removed?

**Comment by kevinbader** [comment]
Integration tests fail on my machine. Tried multiple runs; this came up every time:

```plain
  1) test Given a started RigKafka client, messages can be produced and consumed. (RigKafkaTest)
     test/rig_kafka_test.exs:42
     No message matching :test_message_received after 10000ms.
     The process mailbox is empty.
     code: assert_receive :test_message_received, 10_000
     stacktrace:
       test/rig_kafka_test.exs:62: (test)
```

and this only during the first run:

```plain
 1) test Given response_from is set to Kafka, the http response is taken from the Kafka response topic instead of forwarding the backend's original response. (RigTests.Proxy.ResponseFrom.KafkaTest)
     test/proxy/response_from/kafka_test.exs:47
     ** (HTTPoison.Error) :timeout
     code: %HTTPoison.Response{status_code: res_status, body: res_body} = HTTPoison.get!(request_url)
     stacktrace:
       (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
       test/proxy/response_from/kafka_test.exs:109: (test)
```

File: docs/event-serialization.md [hunk 2]
```diff
@@ -97,13 +97,18 @@ KAFKA_PORT_PLAIN=17092 KAFKA_PORT_SSL=17093 HOST=localhost docker-compose -f int
...
+-e KAFKA_SERIALIZER=avro \
+-e KAFKA_SCHEMA_REGISTRY_HOST=kafka-schema-registry:8081 \
+-e KAFKA_SOURCE_TOPICS=rigRequest \
+-e PROXY_CONFIG_FILE=proxy/proxy.test.json \
+-e PROXY_KAFKA_REQUEST_TOPIC=rigRequest \
+-e PROXY_KAFKA_REQUEST_AVRO=rigRequest-value \
+-e LOG_LEVEL=debug \
+-p 4000:4000 -p 4010:4010 \
+--network kafka_tests_default \
+accenture/reactive-interaction-gateway
```
Comment (kevinbader) [inline docs/event-serialization.md]: works okay, however, below there's this:

> In terminal you should see something like below

and I don't see this, partly because docker runs the container in detached mode, but even with `docker logs -f rig` I don't see the line as described. Does this mean it doesn't work as expected?

**Comment by mmacai** [comment]
> Integration tests fail on my machine. Tried multiple runs; this came up every time:
> 
> ```
>   1) test Given a started RigKafka client, messages can be produced and consumed. (RigKafkaTest)
>      test/rig_kafka_test.exs:42
>      No message matching :test_message_received after 10000ms.
>      The process mailbox is empty.
>      code: assert_receive :test_message_received, 10_000
>      stacktrace:
>        test/rig_kafka_test.exs:62: (test)
> ```
> and this only during the first run:
> 
> ```
>  1) test Given response_from is set to Kafka, the http response is taken from the Kafka response topic instead of forwarding the backend's original response. (RigTests.Proxy.ResponseFrom.KafkaTest)
>      test/proxy/response_from/kafka_test.exs:47
>      ** (HTTPoison.Error) :timeout
>      code: %HTTPoison.Response{status_code: res_status, body: res_body} = HTTPoison.get!(request_url)
>      stacktrace:
>        (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
>        test/proxy/response_from/kafka_test.exs:109: (test)
> ```

First one fails even on master, it's tracked in #201. Second one can't confirm, but maybe caused by the same thing as first one.

File: apps/rig_kafka/lib/rig_kafka/client.ex [hunk 3]
```diff
@@ -76,30 +76,37 @@ defmodule RigKafka.Client do
...
+            "avro/binary" ->
+              data =
+                body
+                |> Serializer.decode_body!("avro", schema_registry_host: schema_registry_host)
+                |> Jason.decode!()
+
+              Map.merge(headers_no_prefix, %{data: data})
+
+            "application/json" ->
               body
```
[the remark this answers is not in the document]
Comment (mmacai) [reply apps/rig_kafka/lib/rig_kafka/client.ex]: True, I'll update avro handler though to return json encoding (not map), seems to me like smaller change than updating stuff related by this change + imo makes more sense to me to adapt avro behavior according to this one.

File: apps/rig_kafka/lib/rig_kafka/client.ex [hunk 4]
```diff
@@ -76,30 +76,37 @@ defmodule RigKafka.Client do
...
-              |> Serializer.decode_body("avro", schema_registry_host)
-              |> Jason.decode!()
 
-            Map.merge(headers_no_prefix, %{data: data})
+            _ ->
+              body
```
[the remark this answers is not in the document]
Comment (mmacai) [reply apps/rig_kafka/lib/rig_kafka/client.ex]: > > Integration tests fail on my machine. Tried multiple runs; this came up every time:
> > ```
> >   1) test Given a started RigKafka client, messages can be produced and consumed. (RigKafkaTest)
> >      test/rig_kafka_test.exs:42
> >      No message matching :test_message_received after 10000ms.
> >      The process mailbox is empty.
> >      code: assert_receive :test_message_received, 10_000
> >      stacktrace:
> >        test/rig_kafka_test.exs:62: (test)
> > ```
> > 
> > 
> > and this only during the first run:
> > ```
> >  1) test Given response_from is set to Kafka, the http response is taken from the Kafka response topic instead of forwarding the backend's original response. (RigTests.Proxy.ResponseFrom.KafkaTest)
> >      test/proxy/response_from/kafka_test.exs:47
> >      ** (HTTPoison.Error) :timeout
> >      code: %HTTPoison.Response{status_code: res_status, body: res_body} = HTTPoison.get!(request_url)
> >      stacktrace:
> >        (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
> >        test/proxy/response_from/kafka_test.exs:109: (test)
> > ```
> 
> First one fails even on master, it's tracked in #201. Second one can't confirm, but maybe caused by the same thing as first one.

Actually probably found the issue in our old test and made the tests more stable.

File: docs/event-serialization.md (hunk 2 above)
Comment (mmacai) [reply docs/event-serialization.md]: Are you sure? Just tested it and I can see:

```
11:05:48.880 [debug] Decoded Avro message="{\"example\":\"test\"}"
application=rig_kafka module=RigKafka.Avro function=decode/2 file=lib/rig_kafka/avro.ex line=29 pid=<0.1935.0>

11:05:48.882 [debug] [:start_object, {:string, "contenttype"}, :colon, {:string, "avro/binary"}, :comma, {:string, "data"}, :colon, :start_object, {:string, "example"}, :colon, {:string, "test"}, :end_object, :comma, {:string, "id"}, :colon, {:string, "069711bf-3946-4661-984f-c667657b8d85"}, :comma, {:string, "rig"}, :colon, :start_object, {:string, "correlation"}, :colon, {:string, "g2dkAA1yaWdAMTI3LjAuMC4xAAAI7AAAAAAB"}, :comma, {:string, "headers"}, :colon, :start_array, :start_array, {:string, "accept"}, :comma, {:string, "*/*"}, :end_array, :comma, :start_array, {:string, "content-length"}, :comma, {:string, "221"}, :end_array, :comma, :start_array, {:string, "content-type"}, :comma, {:string, "application/json"}, :end_array, :comma, :start_array, {:string, "host"}, :comma, {:string, ...}, :end_array, ...]
application=rig module=Rig.EventStream.KafkaToFilter function=kafka_handler/1 file=lib/rig/event_stream/kafka_to_filter.ex line=20 pid=<0.1935.0>
```
